// <auto-generated />
namespace _2011064226_PhamAnhHao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialEmployer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialEmployer));
        
        string IMigrationMetadata.Id
        {
            get { return "202210100646207_Initial Employer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
